// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5zn_it_IA8m96Y9QvZ3bQ-itUCkSwiQ',
    appId: '1:30594640113:android:6014d66ce45d25d72fe150',
    messagingSenderId: '30594640113',
    projectId: 'testsocial-c1160',
    authDomain: 'testsocial-c1160.firebaseapp.com',
    storageBucket: 'testsocial-c1160.appspot.com',
    measurementId: 'G-GD9F7QCP28',
    databaseURL: 'https://testsocial-c1160-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5zn_it_IA8m96Y9QvZ3bQ-itUCkSwiQ',
    appId: '1:30594640113:android:6014d66ce45d25d72fe150',
    messagingSenderId: '30594640113',
    projectId: 'testsocial-c1160',
    storageBucket: 'testsocial-c1160.appspot.com',
    databaseURL: 'https://testsocial-c1160-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5zn_it_IA8m96Y9QvZ3bQ-itUCkSwiQ',
    appId: '1:30594640113:android:6014d66ce45d25d72fe150',
    messagingSenderId: '30594640113',
    projectId: 'testsocial-c1160',
    storageBucket: 'testsocial-c1160.appspot.com',
    databaseURL: 'https://testsocial-c1160-default-rtdb.firebaseio.com',
    iosClientId: '30594640113-ncno94rkf13ro15quk06gf0q9llnkleg.apps.googleusercontent.com',
    iosBundleId: 'com.mvp.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5zn_it_IA8m96Y9QvZ3bQ-itUCkSwiQ',
    appId: '1:30594640113:android:6014d66ce45d25d72fe150',
    messagingSenderId: '30594640113',
    projectId: 'testsocial-c1160',
    storageBucket: 'testsocial-c1160.appspot.com',
    databaseURL: 'https://testsocial-c1160-default-rtdb.firebaseio.com',
    iosClientId: '30594640113-ncno94rkf13ro15quk06gf0q9llnkleg.apps.googleusercontent.com',
    iosBundleId: 'com.mvp.churchApp',
  );
}
